Web Tracker/Controllers/FlowController.cs
using Microsoft.AspNetCore.Mvc;
using WebTracker.Controllers;
using WebTracker.Repositories;
using SignalR_Check;
using WebTracker.Models;
using SignalR_Check.Models;

namespace SignalR_Check.Controllers
{
    public class FlowController : Controller
    {
        IWebsiteRepository _websiteRepository;
        IUserRepository _userRepository;
        IFlowRepository _flowRepository;
        IActionRepository _actionRepository;
        IFlowDataRepository _flowDataRepository;
        ISummaryData _summaryData;
        public FlowController(IWebsiteRepository websiteRepository, IUserRepository userRepository, IFlowRepository flowRepository, IActionRepository actionRepository, IFlowDataRepository flowDataRepository, ISummaryData summaryData)
        {
            _websiteRepository = websiteRepository;
            _userRepository = userRepository;
            _flowRepository = flowRepository;
            _actionRepository = actionRepository;
            _flowDataRepository = flowDataRepository;
            _summaryData = summaryData;
        }
        public IActionResult Index()
        {
            if (HttpContext.Request.Cookies["username"] != null)
            {
                ViewBag.userinfo = HttpContext.Request.Cookies["username"];
                int loggedInUserWebsiteId = int.Parse(HttpContext.Request.Cookies["loggedInUserWebsiteId"]);

                var flow = _flowDataRepository.GetAllFlowDatas()
                    .Join(_flowRepository.GetAllFlows(), p => p.FlowId, u => u.FlowId, (p, u) => new { p, u })
                    .Join(_userRepository.GetAllUsers(), pu => pu.u.UserId, c => c.UserId, (pu, c) => new { pu.p, pu.u, c })
                    .Where(puc => puc.c.WebsiteId == loggedInUserWebsiteId).Select(puc => new { puc.p.Page, puc.p.FlowId }).ToList();
                List<int> uniqnum = flow.Select(u => u.FlowId).Distinct().ToList();
                List<string> contFlows = new List<string>();
                string cf = "";
                foreach (var f in uniqnum)
                {
                    foreach (var fd in flow)
                    {
                        if (fd.FlowId == f)
                        {
                            if (fd.Page == "/")
                            {
                                cf = cf + "Landing Page" + " ➜ ";
                            }
                            else
                            {
                                cf = cf + fd.Page + " ➜ ";
                            }
                        }
                    }
                    contFlows.Add(cf);
                    cf = "";
                }
                ViewBag.Flows = contFlows;
                ViewBag.FlowIDs = uniqnum;
                var Action = _actionRepository.GetAllActions()
                    .Join(_flowRepository.GetAllFlows(), p => p.FlowId, u => u.FlowId, (p, u) => new { p, u })
                    .Join(_userRepository.GetAllUsers(), pu => pu.u.UserId, c => c.UserId, (pu, c) => new { pu.p, pu.u, c })
                    .Where(puc => puc.c.WebsiteId == loggedInUserWebsiteId).Select(puc => new { puc.p.Page, puc.p.FlowId, puc.p.Type, puc.p.Content }).ToList();
                List<string> uniqpage = Action.Select(u => u.Page).Distinct().ToList();
                List<string> contActions = new List<string>();
                List<List<string>> pageactions = new List<List<string>>();
                string pc = "";
                foreach (var f in uniqnum)
                {
                    List<string> list = new List<string>();
                    foreach (var p in uniqpage)
                    {
                        bool first = true;
                        string temp = pc;
                        foreach (var a in Action)
                        {
                            if (a.FlowId == f && a.Page == p)
                            {
                                if (a.Content == "/")
                                {
                                    if (first)
                                    {
                                        first = false;
                                    }
                                    pc = pc + a.Type + "(" + "Landing Page" + ") ➜ ";
                                }
                                else
                                {
                                    if (first)
                                    {
                                        first = false;
                                    }
                                    pc = pc + a.Type + "(" + a.Content + ") ➜ ";
                                }
                            }
                        }
                        if (pc != temp)
                        {
                            list.Add(pc);
                        }
                    }
                    pageactions.Add(list);
                    //contActions.Add(pc);
                    pc = "";
                }
                ViewBag.Actions = pageactions;
                ViewBag.pages = uniqpage;
                List<FlowSummary> flows = _summaryData.GetAllFlows(loggedInUserWebsiteId);
                foreach (var f in flows)
                {
                    string finalFlow = "";
                    for (int i = 0; i < f.FlowSummed.Length; i++)
                    {
                        if (f.FlowSummed[i] == '>')
                        {
                            finalFlow += "➜";
                        }
                        else if (i == f.FlowSummed.Length - 1 && f.FlowSummed[i] == '/')
                        {
                            finalFlow += "LandingPage";
                        }
                        else if (f.FlowSummed[i] == '/' && f.FlowSummed[i + 1] == '>')
                        {
                            finalFlow += "LandingPage";
                        }
                        else
                        {
                            finalFlow += f.FlowSummed[i];
                        }
                    }
                    f.FlowSummed = finalFlow;
                }
                ViewBag.Summary = flows;
                List<ActionSummary> Actions = _summaryData.GetAllActions(loggedInUserWebsiteId);
                foreach (var action in Actions)
                {
                    string finalFlow = "";
                    for (int i = 0; i < action.ActionSummed.Length; i++)
                    {
                        if (action.ActionSummed[i] == '>')
                        {
                            finalFlow += "➜";
                        }
                        else if (action.ActionSummed[i] == '/' && (action.ActionSummed[i + 1] == '[' || action.ActionSummed[i + 1] == ')'))
                        {
                            finalFlow += "LandingPage";
                        }
                        else
                        {
                            finalFlow += action.ActionSummed[i];
                        }
                    }
                    action.ActionSummed = finalFlow;

                }
                ViewBag.ActionSummary = Actions;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }
    }
}

Web Tracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Web Tracker | Dashboard</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <style>
    #chartdiv, #chartdiv1, #chartdiv2, #deviceChart, #osChart {
      width: 100%;
      height: 400px;
      max-width: 100%;
    }
  </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      @*<li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>*@
    </ul>

    <!-- SEARCH FORM -->
    @*<form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>*@

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
            @*<li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
            </li>*@
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">WEB TRACKER</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
        <a asp-action="logout" asp-controller="Account" class="d-block">@ViewBag.userinfo</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
              <a asp-controller="Home" asp-action="index" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a asp-controller="Flow" asp-action="index" class="nav-link active">
                            <i class="nav-icon fas fa-th-large"></i>
                    <p>
                        Website Flow
                    </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
    <div class="wrapper">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    </aside>
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.5
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/dist/js/demo.js"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="~/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="~/plugins/raphael/raphael.min.js"></script>
    <script src="~/plugins/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="~/plugins/jquery-mapael/maps/usa_states.min.js"></script>
    @*<!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- FLOT CHARTS -->
    <script src="../../plugins/flot/jquery.flot.js"></script>
    <!-- FLOT RESIZE PLUGIN - allows the chart to redraw when the window is resized -->
    <script src="../../plugins/flot-old/jquery.flot.resize.min.js"></script>
    <!-- FLOT PIE PLUGIN - also used to draw donut charts -->
    <script src="../../plugins/flot-old/jquery.flot.pie.min.js"></script>*@
    <!-- PAGE SCRIPTS -->
    <script src="~/dist/js/pages/dashboard2.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/map.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/geodata/worldLow.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>